# Generated by Django 5.2.12 on 2026-04-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='pages.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
