# Generated by Django 5.2.12 on 2026-05-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_book_options_alter_book_author_alter_book_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='books_photos/%Y/%m/%d/', verbose_name='Изображение книги'),
        ),
    ]
